apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: dfj77nsdqa3uoe
    type: prometheus
    access: proxy
    url: ${VICTORIAMETRICS_URL}
    isDefault: true
    editable: true

  - name: victoriametrics-logs-datasource
    uid: dfj77se0uvshsd
    type: victoriametrics-logs-datasource
    access: proxy
    url: ${VICTORIALOGS_URL}
    isDefault: false
    editable: true
    jsonData:
      logLevelRules: []
