# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Grafana Image Renderer
version: 0.1.0
slug: grafana-image-renderer
description: Grafana Image Renderer service for rendering panels and dashboards as images
url: https://github.com/JaneJeon/homeassistant-apps/tree/main/grafana-image-renderer
arch:
  - aarch64
  - amd64
init: false
options:
  port: 8081
  auth_token: "-"
  browser_max_width: 1920
  browser_max_height: 1080
  browser_flags: "--disable-dev-shm-usage,--disable-extensions"
schema:
  port: "port?"
  auth_token: "str?"
  browser_max_width: "int?"
  browser_max_height: "int?"
  browser_flags: "str?"
image: "ghcr.io/janejeon/grafana-image-renderer"
